import { defineConfig, devices } from "@playwright/test";

/**
 * Generated by Specra, then owned by you.
 *
 * The base URL comes from the environment so the same suite runs against dev, staging and CI.
 * Nothing here calls Specra: this project runs on its own, which is the point.
 */
export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: Boolean(process.env.CI),
  retries: process.env.CI ? 2 : 0,
  reporter: process.env.CI ? "github" : "list",
  use: {
    baseURL: process.env.BASE_URL ?? "http://localhost:3000",
    trace: "on-first-retry",
    video: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
});
