/**
 * Test parameters, read from the environment.
 *
 * Generated by Specra. Values live in your CI secrets or your local .env — never in
 * this repository, and never in a Specra database.
 */

function read(name: string, required: boolean): string {
  const value = process.env[name];
  if (value === undefined || value === "") {
    if (required) {
      throw new Error(`${name} is not set. Add it to the environment this suite runs in.`);
    }
    return "";
  }
  return value;
}

/** The tenant the account belongs to. */
export const companyCode = (): string => read("COMPANY_CODE", true);

/** Secret. Read from PASSWORD; never logged, never committed. */
export const password = (): string => read("PASSWORD", true);

/** The account the test signs in as. */
export const username = (): string => read("USERNAME", true);
