import type { Locator, Page } from "@playwright/test";

/**
 * LoginPage — /login.
 *
 * Generated by Specra from inspected locators. Edit freely: this file is yours, and a
 * regeneration proposes a diff rather than overwriting your changes.
 */
export class LoginPage {
  constructor(readonly page: Page) {}

  // confidence 0.22
  get button(): Locator {
    return this.page.locator(
      "form > div > div:nth-of-type(2) > div > div:nth-of-type(3) > button",
    );
  }

  // fallback: label COMPANY CODE *
  // confidence 0.90
  get companyCodeInput(): Locator {
    return this.page.getByRole("textbox", { name: "COMPANY CODE *" });
  }

  // fallback: text Log in
  // confidence 0.90
  get logInButton(): Locator {
    return this.page.getByRole("button", { name: "Log in" });
  }

  // fallback: label PASSWORD *
  // confidence 0.90
  get passwordInput(): Locator {
    return this.page.getByRole("textbox", { name: "PASSWORD *" });
  }

  // fallback: label USERNAME *
  // confidence 0.90
  get usernameInput(): Locator {
    return this.page.getByRole("textbox", { name: "USERNAME *" });
  }

  async goto(): Promise<void> {
    await this.page.goto("/login");
  }
}
