import { expect, test } from "@playwright/test";

import { LoginPage } from "../../pages/LoginPage.js";
import { username, password, companyCode } from "../../fixtures/environment.js";

/** TC-6 — generated by Specra from the Test Model. */
test("[Integration Test][Login] TC01 - Verify user logs in successfully with valid credentials @login @integration @smoke", async ({
  page,
}) => {
  // A registered user signs in from the Login page with a valid username, password and company code, and lands on the Home page.
  const loginPage = new LoginPage(page);

  await test.step("Navigate to the Login page [s1-open-login]", async () => {
    await loginPage.goto();
  });
  await test.step("The Username field is displayed [s2-username-visible]", async () => {
    await expect(loginPage.usernameInput).toBeVisible();
  });
  await test.step("The Password field is displayed [s3-password-visible]", async () => {
    await expect(loginPage.passwordInput).toBeVisible();
  });
  await test.step("The Company Code field is displayed [s4-company-visible]", async () => {
    await expect(loginPage.companyCodeInput).toBeVisible();
  });
  await test.step("The Log in button is displayed [s5-login-button-visible]", async () => {
    await expect(loginPage.loginButton).toBeVisible();
  });
  await test.step("Enter the username in the Username field [s6-fill-username]", async () => {
    await loginPage.usernameInput.fill(username());
  });
  await test.step("The Username field contains the entered username [s7-username-value]", async () => {
    await expect(loginPage.usernameInput).toHaveValue("kienpham");
  });
  await test.step("Enter the password in the Password field [s8-fill-password]", async () => {
    await loginPage.passwordInput.fill(password());
  });
  await test.step("The Password field masks its value [s9-password-masked]", async () => {
    await expect(loginPage.passwordInput).toHaveAttribute("type", "password");
  });
  await test.step("Enter the company code in the Company Code field [s10-fill-company]", async () => {
    await loginPage.companyCodeInput.fill(companyCode());
  });
  await test.step("The Company Code field contains the entered code [s11-company-value]", async () => {
    await expect(loginPage.companyCodeInput).toHaveValue("Impex");
  });
  await test.step("Click the Log in button [s12-click-login]", async () => {
    await loginPage.loginButton.click();
  });
  await test.step("The Home page is displayed [s13-home-loaded]", async () => {
    await expect(homePage.root).toBeVisible();
  });
  await test.step("The Login page is left [s14-left-login]", async () => {
    await expect(page).toHaveURL(new RegExp("^(?!.*/login).*$"));
  });
});
