import { expect, test } from "@playwright/test";

import { username, password, displayName } from "../../fixtures/environment.js";

/** TC-5 — generated by Specra from the Test Model. */
test("Verify user logs in successfully with valid credentials @authentication @login @sample", async ({
  page,
}) => {
  // Verify that a user holding valid, active credentials is authenticated and lands on the Home page.
  await test.step("Open the Login page [s1]", async () => {
    await loginPage.goto();
  });
  await test.step("The Username field is visible [s2]", async () => {
    await expect(loginPage.usernameInput).toBeVisible();
  });
  await test.step("The Password field is visible [s3]", async () => {
    await expect(loginPage.passwordInput).toBeVisible();
  });
  await test.step("The Remember me checkbox is visible [s4]", async () => {
    await expect(loginPage.rememberMeCheckbox).toBeVisible();
  });
  await test.step("The Login button is visible [s5]", async () => {
    await expect(loginPage.submitButton).toBeVisible();
  });
  await test.step("Enter the username [s6]", async () => {
    await loginPage.usernameInput.fill(username());
  });
  await test.step("Enter the password [s7]", async () => {
    await loginPage.passwordInput.fill(password());
  });
  await test.step("The Username field holds what was typed [s8]", async () => {
    await expect(loginPage.usernameInput).toHaveValue("qa.user01");
  });
  await test.step("The password is masked [s9]", async () => {
    await expect(loginPage.passwordInput).toHaveAttribute("type", "password");
  });
  await test.step("Click the Login button [s10]", async () => {
    await loginPage.submitButton.click();
  });
  await test.step("Wait for the Home page header to appear [s11]", async () => {
    await expect(homePage.headerUserName).toBeVisible();
  });
  await test.step("The browser is on the Home page [s12]", async () => {
    await expect(page).toHaveURL(new RegExp("^.*/(home|dashboard)?/?$"));
  });
  await test.step("The header shows the display name [s13]", async () => {
    await expect(homePage.headerUserName).toHaveText("qa.user01");
  });
});
